server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # 暴露 prometheus 指标
  endpoint:
    prometheus:
      enabled: true  # 显式启用 prometheus endpoint
  prometheus:
    metrics:
      export:
        enabled: true

dubbo:
  application:
    name: pay-service
    qos-enable: false
  registry:
    address: nacos://nacos-headless.default.svc.cluster.local:8848
    register-mode: instance
  protocol:
    name: dubbo
    port: 20887

knife4j:
  enable: true
  openapi:
    title: PayGateway 支付网关
    description: PayGateway 支付网关 接口文档
    version: 1.0.0
    license: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0
    contact:
      name: Sr.Zhou
      email: 2177922023@qq.com
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.zhouzhou.cloud.controller